### ISSUE TITLE
Vivecraft 1.16 crashes on launch

### ISSUE THREAD

**Issue by TheSpooky5311** [jrbudda/Vivecraft_111#64] opened 2020-08-17 17:54 UTC
So i just tried to start the game with my VR but it crashed. I did it a few times and reinstalled Vivecraft but I cant seem to be able to fix it. If I start the game without my VR it loads and when it's done it tells me that it doesnt recognize a VR connected.

**Comment by jrbudda** [comment] 2020-08-17 18:43
wrong github and duplicate of https://github.com/jrbudda/Vivecraft_116/issues/2

**Closed by jrbudda** 2020-08-17 18:43 UTC
